version: '3'
services: 
    api1:
        build: ./api-a
        ports:
            - "8000:8000"
        depends_on:
            - api2
        network_mode: host
    api2:
        build: ./api-b
        ports: 
            - "5002:5002"
        network_mode: host
